### ISSUE TITLE
Trying to get mipi camera working with Linaro 16.06 Release

### ISSUE THREAD

**Issue by RobGries** [Kevin-WSCU/96Boards-Camera#6]
Hello,

I'm having trouble with the 16.06 release and the AISTARVISION MIPI Adapter V2.0. I am attempting to test video capture with FFMPEG obtained from apt-get in the 16.06 release and keep getting the same error:
```
$ffmpeg -i /dev/video0 -c:v libx264 -preset slow -crf 22 -c:a none output.mkv
[video4linux2,v4l2 @ 0x55b0751e00] ioctl(VIDIOC_G_INPUT): Inappropriate ioctl for device
/dev/video0: Inappropriate ioctl for device
```

Dmesg output:
```
[   64.450422] qcom-camss 1b0ac00.camss: ispif_set_power: Enter, on = 1
[   64.450517] qcom-camss 1b0ac00.camss: ispif_set_power: Exit, on = 1
[   64.455983] qcom-camss 1b0ac00.camss: msm_vfe_subdev_set_power: Enter, on = 1
[   64.463248] qcom-camss 1b0ac00.camss: VFE HW Version = 0x10030000
[   64.469180] qcom-camss 1b0ac00.camss: msm_vfe_subdev_set_power: Exit, on = 1
[   64.475549] qcom-camss 1b0ac00.camss: ispif_set_power: Enter, on = 0
[   64.482536] qcom-camss 1b0ac00.camss: ispif_set_power: Exit, on = 0
[   64.488706] qcom-camss 1b0ac00.camss: msm_vfe_subdev_set_power: Enter, on = 0
[   64.495712] qcom-camss 1b0ac00.camss: msm_vfe_subdev_set_power: Exit, on = 0
```

Any help would be appreciated,

Rob

**Comment by RobGries** [comment]
I have now switched over to the 16.09 build, and rebuilt the kernel. 

The rebuilt kernel is using the  apq8016.dtsi file from Dragonboard410C-Camera/Pre-built/Debian_16.09/SingleCamera/ 

The kernel boots properly and sees the camera without errors during boot time, however the media-ctl pipelines mentioned by linaro do not work properly. But this is ok, since the AiStarVision board has two separate camera interfaces, and a different i2c address so the following media-ctl pipelines appear to work:
`
sudo media-ctl -v -d /dev/media1 -l '"msm_csiphy0":1->"msm_csid0":0[1],"msm_csid0":1->"msm_ispif0":0[1]'

sudo media-ctl -v -d /dev/media1 -V '"ov5645 1-0076":0[fmt:UYVY2X8/1920x1080],"msm_csiphy0":0[fmt:UYVY2X8/1920x1080],"msm_csid0":0[fmt:UYVY2X8/1920x1080]'

`

Now my issue is that when I attempt to capture from the camera, using the following gstreamer pipeline
`
gst-launch-1.0 v4l2src device=/dev/video0 num-buffers=1 ! 'video/x-raw,format=UYVY,width=1920,height=1080,framerate=30/1' ! jpegenc ! filesink location=image01.jpg
`

Gstreamer either hangs while playing the pipeline, or causes a panic with the following errors in my kernel log:
`
[  222.216065] qcom-camss 1b0ac00.camss: Vfe halt timeout
[  222.316066] qcom-camss 1b0ac00.camss: Vfe halt timeout
[  222.415992] qcom-camss 1b0ac00.camss: Vfe halt timeout
[  222.442689] qcom-camss 1b0ac00.camss: Output is running
[  222.442713] qcom-camss 1b0ac00.camss: Fail to enable vfe outputs
[  235.805218] ------------[ cut here ]------------
[  235.805279] WARNING: at drivers/media/v4l2-core/videobuf2-core.c:850
[  235.808924] Modules linked in: r8152 bnep wcn36xx

[  235.819871] CPU: 0 PID: 3884 Comm: gst-launch-1.0 Not tainted 4.4.23-linaro-lt-qcom #2
[  235.821428] Hardware name: Qualcomm Technologies, Inc. APQ 8016 SBC (DT)
[  235.829161] task: ffffffc034986000 ti: ffffffc034bf0000 task.ti: ffffffc034bf0000
[  235.836030] PC is at vb2_buffer_done+0x160/0x19c
[  235.843402] LR is at vfe_flush_dmabufs+0xd0/0x120
[  235.848078] pc : [<ffffffc0005bcda0>] lr : [<ffffffc0005c6e3c>] pstate: 800001c5
[  235.852677] sp : ffffffc034bf3ab0
[  235.860137] x29: ffffffc034bf3ab0 x28: 0000000000000000 
[  235.868463] x27: 0000000000000001 x26: 0000000000000140 
[  235.873759] x25: ffffffc0357e1948 x24: ffffffc0357e138c 
[  235.879054] x23: 0000000000000007 x22: ffffffc034819c00 
[  235.884349] x21: ffffffc034818400 x20: ffffffc0357e1790 
[  235.889643] x19: ffffffc0357e1790 x18: 0000007fe651b250 
[  235.894940] x17: 0000007f79f4acd0 x16: ffffffc0001c9c10 
[  235.900234] x15: 0000007f79fcc588 x14: 0000000000000000 
[  235.905530] x13: ffffffffff000000 x12: ffffffffffffffff 
[  235.910824] x11: 0000000000000003 x10: 7f7f7f7f7f7f7f7f 
[  235.916119] x9 : fefeff2f6863715e x8 : 0000000035c7612c 
[  235.921414] x7 : ffffffffffffffff x6 : 1b1508ffffffffff 
[  235.926709] x5 : 0000000000000000 x4 : ffffffc0357e17a8 
[  235.932005] x3 : ffffffc0357e1960 x2 : ffffffc0357e1960 
[  235.937298] x1 : 0000000000000007 x0 : 0000000000000000 

[  235.942772] ---[ end trace aaf02699e0a0f677 ]---
[  235.944340] Call trace:
[  235.948951] [<ffffffc0005bcda0>] vb2_buffer_done+0x160/0x19c
[  235.951131] [<ffffffc0005c6e3c>] vfe_flush_dmabufs+0xd0/0x120
[  235.957032] [<ffffffc0005c8ffc>] video_stop_streaming+0x24/0x2c
[  235.962671] [<ffffffc0005bd15c>] __vb2_queue_cancel+0x30/0x13c
[  235.968398] [<ffffffc0005be550>] vb2_core_streamoff+0x44/0xa8
[  235.974302] [<ffffffc0005c053c>] vb2_streamoff+0x3c/0x60
[  235.980121] [<ffffffc0005c9198>] video_streamoff+0xc0/0x194
[  235.985499] [<ffffffc0005a8154>] v4l_streamoff+0x20/0x28
[  235.990796] [<ffffffc0005abe38>] __video_do_ioctl+0x240/0x2b0
[  235.996350] [<ffffffc0005aba98>] video_usercopy+0x328/0x46c
[  236.001991] [<ffffffc0005abbf0>] video_ioctl2+0x14/0x1c
[  236.007371] [<ffffffc0005a6e60>] v4l2_ioctl+0xe0/0x110
[  236.012585] [<ffffffc0001c99a8>] do_vfs_ioctl+0x374/0x5dc
[  236.017792] [<ffffffc0001c9c94>] SyS_ioctl+0x84/0x98
[  236.023260] [<ffffffc000085e30>] el0_svc_naked+0x24/0x28
[  236.028412] ------------[ cut here ]------------
[  236.033577] WARNING: at drivers/media/v4l2-core/videobuf2-core.c:850
[  236.038175] Modules linked in: r8152 bnep wcn36xx

[  236.049124] CPU: 0 PID: 3884 Comm: gst-launch-1.0 Tainted: G        W       4.4.23-linaro-lt-qcom #2
[  236.050685] Hardware name: Qualcomm Technologies, Inc. APQ 8016 SBC (DT)
[  236.059803] task: ffffffc034986000 ti: ffffffc034bf0000 task.ti: ffffffc034bf0000
[  236.066491] PC is at vb2_buffer_done+0x160/0x19c
[  236.073868] LR is at vfe_flush_dmabufs+0xe0/0x120
[  236.078548] pc : [<ffffffc0005bcda0>] lr : [<ffffffc0005c6e4c>] pstate: 800001c5
[  236.083145] sp : ffffffc034bf3ab0
[  236.090605] x29: ffffffc034bf3ab0 x28: 0000000000000000 
[  236.098932] x27: 0000000000000001 x26: 0000000000000140 
[  236.104227] x25: ffffffc0357e1948 x24: ffffffc0357e138c 
[  236.109521] x23: 0000000000000007 x22: ffffffc034819a00 
[  236.114817] x21: ffffffc034818600 x20: ffffffc0357e1790 
[  236.120112] x19: ffffffc0357e1790 x18: 0000007fe651b250 
[  236.125408] x17: 0000007f79f4acd0 x16: ffffffc0001c9c10 
[  236.130703] x15: 0000007f79fcc588 x14: 0000000000000000 
[  236.135998] x13: ffffffffff000000 x12: ffffffffffffffff 
[  236.141292] x11: 0000000000000003 x10: 7f7f7f7f7f7f7f7f 
[  236.146588] x9 : fefeff2f6863715e x8 : 0000000035c7612c 
[  236.151884] x7 : ffffffffffffffff x6 : 1b1508ffffffffff 
[  236.157178] x5 : 0000000000000000 x4 : ffffffc0357e17a8 
[  236.162474] x3 : ffffffc0357e1960 x2 : ffffffc0357e1960 
[  236.167768] x1 : 0000000000000007 x0 : 0000000000000000 

[  236.173241] ---[ end trace aaf02699e0a0f678 ]---
[  236.174806] Call trace:
[  236.179416] [<ffffffc0005bcda0>] vb2_buffer_done+0x160/0x19c
[  236.181596] [<ffffffc0005c6e4c>] vfe_flush_dmabufs+0xe0/0x120
[  236.187502] [<ffffffc0005c8ffc>] video_stop_streaming+0x24/0x2c
[  236.193139] [<ffffffc0005bd15c>] __vb2_queue_cancel+0x30/0x13c
[  236.198867] [<ffffffc0005be550>] vb2_core_streamoff+0x44/0xa8
[  236.204770] [<ffffffc0005c053c>] vb2_streamoff+0x3c/0x60
[  236.210590] [<ffffffc0005c9198>] video_streamoff+0xc0/0x194
[  236.215966] [<ffffffc0005a8154>] v4l_streamoff+0x20/0x28
[  236.221264] [<ffffffc0005abe38>] __video_do_ioctl+0x240/0x2b0
[  236.226818] [<ffffffc0005aba98>] video_usercopy+0x328/0x46c
[  236.232459] [<ffffffc0005abbf0>] video_ioctl2+0x14/0x1c
[  236.237840] [<ffffffc0005a6e60>] v4l2_ioctl+0xe0/0x110
[  236.243052] [<ffffffc0001c99a8>] do_vfs_ioctl+0x374/0x5dc
[  236.248259] [<ffffffc0001c9c94>] SyS_ioctl+0x84/0x98
[  236.253728] [<ffffffc000085e30>] el0_svc_naked+0x24/0x28
[  236.364103] qcom-camss 1b0ac00.camss: Vfe halt timeout
`
Are you getting similar results? Am I missing some crucial detail? I think that I followed what was mentioned on the home page of this repo. I asked a similar question during yesterday's 96Boards Open Hours and Rob Wolff referred me to you guys.

Thanks,

Rob

**Comment by Kevin-WSCU** [comment]
Hi Rob
           We are very sorry,just saw your issue posted here.But i am glad you already solved the problem,saw your post in the 96Boards forum. So i am closing this issue

Regards,
Kevin
